export { default as Home } from './Home'
export { default as Movies } from './Movies'
export { default as Rentals } from './Rentals'
export { default as SignIn } from './SignIn'
export { default as Register } from './Register'
export { default as NotFound } from './NotFound'