configuration:
  swagger:
    app: 'Frent'
    description: 'A film renting system'
    developer: 'Edin Bajrić'
    email: 'edin.bajric@stu.ibu.edu.ba'
spring:
  data:
    mongodb:
      uri: mongodb+srv://edinweb:webengineering@cluster1.hggqskb.mongodb.net/?retryWrites=true&w=majority
      database: frent
email:
  mailgun:
    domain: https://api.mailgun.net/v3/sandbox83d964e9301043caacff4697edc3298f.mailgun.org
    from-email: Film Renting System <mailgun@sandbox83d964e9301043caacff4697edc3298f.mailgun.org>
    username: api
    password: 2ddeb646ee8c12f3a3f9a017457e7b60-3750a53b-c6c5c91f
security:
  jwt:
    secret: 'HucVcLqiV5Jv442U3N9N9RhyXQqf2wwYtZKUYpJzrecbCEZyNAqFfTGF55PW7h9T'